site_name: FreshNest
site_url: https://lovish-ab.github.io/grocery_delivery_docs/
theme:
  name: material
  palette:
    primary: indigo
    accent: orange
nav:
  - Introduction: index.md
  - Functional Documentation: functional.md
  - Use Case Documentation: usecase.md
  - Technical Design:
      - Technical Stack: technical_stack.md
      - Schema Design: schema_design.md
      - Cloud Architecture: cloud_architecture.md
      - Data Flow Diagram: data_flow.md
      - Authentication & Authorization Flow: auth_flow.md
      - FreshNest â€“ Unit Test Plan: test_plan.md


plugins:
  - mermaid2