site_name: My Docs
site_name: Grocery Delivery Platform
theme:
  name: material
  palette:
    primary: indigo
    accent: orange
nav:
  - Introduction: index.md
  - Functional Documentation: functional.md
  - Use Case Documentation: usecase.md
  - Technical Design:
      - Technical Stack: technical_stack.md
      - Schema Design: schema_design.md
      - Cloud Architecture: cloud_architecture.md
      - Data Flow Diagram: data_flow.md
      - Authentication & Authorization Flow: auth_flow.md


plugins:
  - mermaid2